title: "Фабрики METADATA"
description: "Структура сети фабрик METADATA."
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: assets/css/

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "metacraft"
  twitter: "metadatafdn"
